### ISSUE TITLE
Question/addition to (closed )issue #187

### ISSUE THREAD

**Issue by Calimerorulez** [dennissiemensma/dsmr-reader#529]
Hi Dennis,

Ik heb de firmware van mijn ESP-Easy geupgrade naar de laatste versie, en nu krijg ik (stom van me) API errors:

dsmrreader.log:

```
[2018-10-03 21:10:16,335] WARNING  @ v1 | API validation failed with POST data: <QueryDict: {'telegram': ['']}>
[2018-10-03 21:10:17,297] WARNING  @ services | Rejected telegram (base64 encoded): '
[2018-10-03 21:10:17,299] ERROR    @ services | Content or CRC data not found
Traceback (most recent call last):
  File "/home/dsmr/dsmr-reader/dsmr_datalogger/services.py", line 189, in telegram_to_reading
    verify_telegram_checksum(data=data)
  File "/home/dsmr/dsmr-reader/dsmr_datalogger/services.py", line 123, in verify_telegram_checksum
    raise InvalidTelegramError('Content or CRC data not found')
dsmr_datalogger.exceptions.InvalidTelegramError: Content or CRC data not found
```

Mijn Python programma gooit dit eruit:

```
Read telegram:
/XMX5LGBBFG1009119848

1-3:0.2.8(42)
0-0:1.0.0(181003211857S)
0-0:96.1.1(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
1-0:1.8.1(004071.386*kWh)
1-0:1.8.2(004064.277*kWh)
1-0:2.8.1(000000.000*kWh)
1-0:2.8.2(000000.000*kWh)
0-0:96.14.0(0002)
1-0:1.7.0(00.580*kW)
1-0:2.7.0(00.000*kW)
0-0:96.7.21(00008)
0-0:96.7.9(00001)
1-0:99.97.0(1)(0-0:96.7.19)(160803065734S)(0000007136*s)
1-0:32.32.0(00000)
1-0:52.32.0(00000)
1-0:72.32.0(00001)
1-0:32.36.0(00000)
1-0:52.36.0(00000)
1-0:72.36.0(00000)
0-0:96.13.1()
0-0:96.13.0()
1-0:
Sending telegram to: http://192.168.188.5:8081/api/v1/datalogger/dsmrreading
[!] API error: Failed to parse telegram
Read telegram:
31.7.0(000*A)
1-0:51.7.0(000*A)
1-0:71.7.0(003*A)
1-0:21.7.0(00.008*kW)
1-0:41.7.0(00.003*kW)
1-0:61.7.0(00.568*kW)
1-0:22.7.0(00.000*kW)
1-0:42.7.0(00.000*kW)
1-0:62.7.0(00.000*kW)
0-1:24.1.0(003)
0-1:96.1.0(xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
0-1:24.2.1(181003210000S)(01731.273*m3)
!5598

```

Het python script ziet er zo uit:

```
def main():
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((HOST, PORT))

    while True:
        socket_data = s.recv(1024)
        telegram = str(socket_data, 'utf-8')

        print('Read telegram:')

        for current_server in API_SERVERS:
            api_url, api_key = current_server
            print(telegram)
            print('Sending telegram to:', api_url)
            send_telegram(telegram, api_url, api_key)

        sleep(1)


def send_telegram(telegram, api_url, api_key):
    response = requests.post(
        api_url,
        headers={'X-AUTHKEY': api_key},
        data={'telegram': telegram},
    )

    if response.status_code not in (200, 201):
        print('[!] API error: {}'.format(response.text))


if __name__ == '__main__':
    main()
```

Iemand een idee? :-)

_Originally posted by @Calimerorulez in https://github.com/dennissiemensma/dsmr-reader/issue_comments#issuecomment-426766314_

**Comment by dennissiemensma** [comment]
Het script lijkt geen rekening te houden met het begin en eind van telegrammen. De base64-string uit je foutmelding, bevat tevens een gedeeltelijk telegram:
```
31.7.0(000*A)\r\n
1-0:51.7.0(000*A)\r\n
1-0:71.7.0(003*A)\r\n
1-0:21.7.0(00.007*kW)\r\n
1-0:41.7.0(00.003*kW)\r\n
1-0:61.7.0(00.585*kW)\r\n
1-0:22.7.0(00.000*kW)\r\n
1-0:42.7.0(00.000*kW)\r\n
1-0:62.7.0(00.000*kW)\r\n
0-1:24.1.0(003)\r\n
0-1:96.1.0(4730303235303033323536353338333135)\r\n
0-1:24.2.1(181003210000S)(01731.273*m3)\r\n
!8107
```

Hier staat een voorbeeld van een script dat er wel rekening mee houdt: https://github.com/dennissiemensma/dsmr-reader/blob/master/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py

Specifiek regel 56 tot 91.

**Comment by dennissiemensma** [comment]
Top, goed om te horen. Dus het werkt nu weer naar behoren?

*Ik heb de serienummers net weggehaald uit mijn eerdere comment en je initiele post.*
