### ISSUE TITLE
Prevent tests from failing due to moment of execution

### ISSUE THREAD

**Issue by dennissiemensma** [dennissiemensma/dsmr-reader#88]
Only seem to fail around midnight. Solution is to mock `timezone.now()`

```
.....................F............................................................................F..SF.......S...........
======================================================================
FAIL: Test whether backups are restricted by one backup per day.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.4.2/lib/python3.4/unittest/mock.py", line 1136, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/dennissiemensma/dsmr-reader/dsmr_backup/tests/test_services.py", line 61, in test_check_interval_restriction
    self.assertTrue(create_backup_mock.called)
AssertionError: False is not true

======================================================================
FAIL: test_analyze_service_clear_cache (dsmr_stats.tests.test_services.TestServices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.4.2/lib/python3.4/unittest/mock.py", line 1136, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/dennissiemensma/dsmr-reader/dsmr_stats/tests/test_services.py", line 119, in test_analyze_service_clear_cache
    self.assertTrue(clear_cache_mock.called)
AssertionError: False is not true

======================================================================
FAIL: test_flush (dsmr_stats.tests.test_services.TestServices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dennissiemensma/dsmr-reader/dsmr_stats/tests/test_services.py", line 123, in test_flush
    self.assertTrue(DayStatistics.objects.exists())
AssertionError: False is not true
```

**Comment by dennissiemensma** [comment]
I've applied `@mock.patch('django.utils.timezone.now')` but it's hard to verify that it works. So I'll push the branch and have Travis re-build and test it later, just after midnight.

**Comment by dennissiemensma** [comment]
Still fails:

```
======================================================================
FAIL: test_analyze_service_clear_cache (dsmr_stats.tests.test_services.TestServices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.3.5/lib/python3.3/unittest/mock.py", line 1087, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/dennissiemensma/dsmr-reader/dsmr_stats/tests/test_services.py", line 123, in test_analyze_service_clear_cache
    self.assertTrue(clear_cache_mock.called)
AssertionError: False is not true
======================================================================
FAIL: test_flush (dsmr_stats.tests.test_services.TestServices)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dennissiemensma/dsmr-reader/dsmr_stats/tests/test_services.py", line 127, in test_flush
    self.assertTrue(DayStatistics.objects.exists())
AssertionError: False is not true
```

**Comment by dennissiemensma** [comment]
https://travis-ci.org/dennissiemensma/dsmr-reader/builds/115984382

**Comment by dennissiemensma** [comment]
I think I've found the issue. Tonight after midnight new attempt.

**Comment by dennissiemensma** [comment]
Seems fixed :]

https://travis-ci.org/dennissiemensma/dsmr-reader/builds/116186593
